[package]
name = "rust-template-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "命令行入口"

[lints]
workspace = true

[[bin]]
name = "rust-template"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[dependencies]
clap.workspace = true
oss-core.workspace = true
